// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrscOFx_HYvao22juS6kSqM2zz28TrxtQ',
    appId: '1:275326816450:web:1f8fbe7024f0de957aeb5b',
    messagingSenderId: '275326816450',
    projectId: 'planit-9d690',
    authDomain: 'planit-9d690.firebaseapp.com',
    storageBucket: 'planit-9d690.appspot.com',
    measurementId: 'G-VL763YYP9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL5dzEZh_E9RATDe1IdteNRTliXka9_tA',
    appId: '1:275326816450:android:6a4ed341067379707aeb5b',
    messagingSenderId: '275326816450',
    projectId: 'planit-9d690',
    storageBucket: 'planit-9d690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaLaGM9gZZsQfD6tvnER5c1BPS-TQKl6s',
    appId: '1:275326816450:ios:974249661e305db17aeb5b',
    messagingSenderId: '275326816450',
    projectId: 'planit-9d690',
    storageBucket: 'planit-9d690.appspot.com',
    iosClientId: '275326816450-oesmule02fdb44gg0euhlets86l2a7jk.apps.googleusercontent.com',
    iosBundleId: 'com.project.planit',
  );
}
